# Generated content
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: Copyright © metaeffekt GmbH 2022-2025. All rights reserved.

canonicalName: "Simplified Artistic License (eNetwizard Content Application Server)"
category: "Simplified Artistic License"
shortName: "Simplified Artistic License (eNetwizard Content Application Server)"

canonicalNameHistory:
  - "Simplified Artistic License"
  - "Simplified Artistic License (eNetwizard Content Management Server)"

osiStatus: "unclear"

