# Generated content
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: Copyright © metaeffekt GmbH 2022-2024. All rights reserved.

canonicalName: "Sencha FLOSS Application Exception 1.04"
category: "Sencha FLOSS Exception"
shortName: "Sencha-FLOSS-Exception-1.04"

canonicalNameHistory:
  - "Sencha Open Source Floss Exception (GPL 3.0)"

type: "exception"

otherIds: 
  - "scancode:sencha-app-floss-exception"
