# Generated content
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: Copyright © metaeffekt GmbH 2022-2024. All rights reserved.

canonicalName: "Slint Royalty-free Desktop and Web Applications License 1.0.1"
category: "Slint Royalty-free Desktop and Web Applications"
shortName: "Slint-Royalty-Free-1.0.1"

alternativeNames:
  - "Slint Royalty-free Desktop and Web Applications License, version 1.0.1"

otherIds: 
  - "scancode:slint-royalty-free-1.0"
